services:
  postgres:
    image: postgres:17.5-alpine3.21
    container_name: express-expense-tracker-postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - express-expense-tracker-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8.2.0-alpine
    container_name: express-expense-tracker-redis
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - express-expense-tracker-redis-data:/data

volumes:
  express-expense-tracker-postgres-data:
  express-expense-tracker-redis-data:
